### ISSUE TITLE
Inconsistency of tissue-specific alpha values

### ISSUE THREAD

**Issue by jkosciessa** [Donders-Institute/PRESTUS#40]
Hi all,
I noticed inconsistent comments in the [config.yaml](https://github.com/Donders-Institute/PRESTUS/blob/05146df2186feee700709b48727170f2c47fbc5b/configs/default_config.yaml#L148), and a potential source for errors when setting the attenuation coefficient. Despite presumed dependence on the fundamental frequency, values are currently hardcoded and relate to 250kHz fundamental frequency (cohering with `source_freq_hz`) instead of the specified `default_freq` of 500k. These parameters can be overwritten by a study-specific script, but this seems like a pretty significant source of potential deviations in acoustic intensity and heating. Would be best to always calculate frequency-specific values, or at least document this as a specification to look out for. 

Here is @eleonoracarpino's original comments in our internal channels (12th Oct. 2023):

> hello simulations people! we have noticed that the skull alpha coefficients that we have been using in the simulations are not a really good fit. therefore, from now on we would suggest to calculate your skull alpha coefficients as follow:

```
medium.alpha_power = 2 
medium.alpha_coeff = 13.3 * (f [MHz]) / (f [MHz])^2 
```

> where f [MHz] is the fundamental frequency expressed in MHz, so either 0.5 or 0.25 for our transducers
some info: 13.3 dB/ (MHz . cm) is a good estimate of the attenuation across the whole skull bone (assuming y = 1) for all frequencies. and we choose y = 2 for the simplicity of the calculations in k-wave. This will effect the simulations giving us lower values of isppa in the brain, because for example for the 250 kHz transducer the new medium.alpha_coeff = 53.2, while before we had 4 or 8.  notice also that this value is unique for the whole skull and does not allow us to distinguish between cortical and trabecular bone; we found out talking with Brad; they don't have a good estimate for cortical vs trabecular but they have a general estimate for the skull (which is easier to get because you just send a wave trough the skull and measure what it remains on the other side of the skull). they also run their simulations with a unique value (and they are in parallel developing the pseudoCT to overcome this). The assumption is that 13.3 is a good estimate for all frequencies. Therefore the relationship 13.3 * f^1 = alpha_coeff * f^2 holds; for the 500 kHz transducer, new medium.alpha_coeff = 26.2 according to this formula, but other methods are possible in this case because there is more data available

**Comment by jkosciessa** [comment]
Just noticed that the updated values cited above are also a feature of the updated branch that merged @eleonoracarpino's changes. Both setups (see [updated default.yaml waiting to be merged](https://github.com/jkosciessa/PRESTUS/blob/ad1870a27f5b7ccb91760af92203387d57e6faba/configs/default_config.yaml#L146)) would be inconsistent with our target settings as described in the comment above.

**Comment by jkosciessa** [comment]
The current comment explains `alpha_0_true` as 
`alpha_0 in alpha = alpha_0*frequency^alpha_power`.

Not sure if this is true, or whether this directly specifies the `alpha_coeff `.

**Comment by jkosciessa** [comment]
As per the example above:

    freq = 500000
    medium.alpha_0_true = 13.3/(freq/1e6); % = 26.6 | refered to as alpha_coeff above; *(f [MHz]) / (f [MHz])^2 can be simplified into  /f [MHz]
    medium.alpha_power_true = 2
    alpha_db_cm = medium.alpha_0_true*((freq/1e6).^medium.alpha_power_true)
    
Thus, `alpha_db_cm` will scale according to fundamental frequency.

**Comment by jkosciessa** [comment]
Perhaps related to this, I wonder whether there is a significant bug regarding the alpha values. In multiple parts of the current code, the medium mask creation seems to not extract the proper ```alpha_0 value``` from the config, but rather ```alpha_power_true``` (e.g., see [here](https://github.com/Donders-Institute/PRESTUS/blob/05146df2186feee700709b48727170f2c47fbc5b/functions/setup_medium.m#L59)). Given that across tissue types, ```alpha_power_true=1.2``` in the past and based on the rationale above ```alpha_power_true=2``` now, this would intuitively mean that absorption was overestimated in water, skin, and brain, and underestimated in the skull.

**Comment by jkosciessa** [comment]
Here is the table with the ITRUSST benchmarks, with the only change based on my reading of Eleonora's discussion above being that alpha at 500 kHz should be updated to 26.2 for both cortical and trabecular bone. 

![Screenshot 2024-07-03 at 16 35 51](https://github.com/Donders-Institute/PRESTUS/assets/40263608/d8de9d47-80bd-47cd-9e39-9f0317b10059)

**Comment by jkosciessa** [comment]
Based on these values, the following ```alpha_0_true``` should be used in combination with ```alpha_power_true=1```

```
f = 0.5 % 500 kHz [data reported in benchmarks]
alpha_power_true = 1
0.2/ f^alpha_power_true = 0.4
0.3/ f^alpha_power_true = 0.6
13.3/ f^alpha_power_true = 26.6
```

**Comment by jkosciessa** [comment]
Based on Fig 2 in https://pubs.aip.org/asa/jasa/article/136/4/1499/905255/Modeling-power-law-absorption-and-dispersion-in, absorption coefficients should increase with fundamental frequency. My current results rather double the absorption for 500 kHz. Spec still wrong.

**Comment by jkosciessa** [comment]
<img width="710" alt="Screenshot 2024-07-04 at 09 37 54" src="https://github.com/Donders-Institute/PRESTUS/assets/40263608/f33a4c7a-6e89-4fd5-b8ee-426305fdc021">

From Carpino et al. (2024). Transcranial ultrasonic stimulation of the human amygdala to modulate threat learning. MSc thesis.

The absorption coefficients in the ```updated``` branch would now match this reported specification for the skull, while skin and brain absorption coefficients would be double what is reported here, given that they have been specified in the default config for 500 kHz instead of 1 MHz. Note for instance that the default config specified alpha0 for an exponent of 1.2 (see [here](https://github.com/Donders-Institute/PRESTUS/blob/05146df2186feee700709b48727170f2c47fbc5b/configs/default_config.yaml#L174)). Alpha0 is then internally always rescaled according to an exponent of 2 as reported in the table. But I am not sure whether this rescaling had been accounted for in the reported values.

Also, whether the error of reading in ```a0 = y``` also affected the simulations Eleonora ran would be useful to check.

**Comment by jkosciessa** [comment]
Based on my reading of the ITRUSST benchmarks at 500 kHz, the 500 kHz values should look like follows:

### brain
0.6 x 0.5^1 = **1.2** x 0.5^2 = 0.3
### skin
0.4 x 0.5^1 = **0.8** x 0.5^2 = 0.2
### bone
26.6 x 0.5^1 = **53.2** x 0.5^2 = 13.3

So the brain/skin values in Eleonora's table should have been doubled when moving to a coefficient of 2. I also think the bone coefficient should be halved, as 13.3 is the attenuation per MHz. Per her equation above:

### bone
13.3 x 0.5^1 = **26.6** x 0.5^2 = 6.65

**Comment by jkosciessa** [comment]
RE: pseudoCT, the ```alpha``` created based on the HU conversion, should already be the attenuation at 500 kHz based on the [supplementary material](https://ars.els-cdn.com/content/image/1-s2.0-S1935861X23008409-mmc1.pdf) by Yakuub et al.; in @eleonoracarpino's implementation those would be turned into the ```alpha0``` prefactors instead, and thus would depend on the absorption coefficient exponent ```𝑦```.

**Comment by jkosciessa** [comment]
Just a bit more background info on how the parameters work within the pipeline:

```setup_medium``` will convert the specified alpha prefactors and exponents to align with a [fixed exponent](https://github.com/Donders-Institute/PRESTUS/blob/05146df2186feee700709b48727170f2c47fbc5b/functions/setup_medium.m#L80) and the specified sound speed. The function ```fitPowerLawParamsMulti``` can provide an optional output of the effective tissue attenuation ```alpha```.

In theory, as long as prefactors and exponents in the config are specified to result in the desired attenuation at the specified fundamental frequency, this conversion should not have too much of an impact. I am not yet convinced that it doesn't have an impact in practice, e.g., by affecting the stability of solutions.

**Comment by jkosciessa** [comment]
Sounds like a good feature improvement. Intuitively, it should also be possible to settle on one particular value that holds across frequencies. Ultimately, the formula already considers fundamental frequency (alpha = a x freq ^ b). The problem is that we then also have to have a valid-ish estimate of exponent b (which now is chosen arbitrarily to match the fundamental frequency of interest).

**Comment by KTZ228** [comment]
I wasn't aware that it might be possible to settle on a set of values that hold for all fundamental frequencies. In that scenario using one set for all frequencies would indeed be preferred. However, if we cannot find a way to not vary b for different frequencies the proposed solution could be a foolproof fit.

**Comment by jkosciessa** [comment]
I wonder whether the following may serve as a general definition:
```
medium:
  water:
    sound_speed: 1500 # [m/s] ITRUSST benchmarks 
    density: 994 # [kg/m^3] Tissue Properties DB or waterDensity(37) function in kWave
    alpha_0_true: 0  # assumes no absorption in water, so no heating
    alpha_power_true: 2
    thermal_conductivity: 0.60 # [W/m/°C] Tissue Properties DB
    specific_heat_capacity: 4178 # [J/kg/°C] Tissue Properties DB
  skull: # cortical bone 
    sound_speed: 2800 # [m/s], ITRUSST benchmarks 
    density: 1850 # [kg/m^3], ITRUSST benchmarks
    alpha_0_true: 13.3 # Pinton et al., 2011 [note: overestimates heating]
    alpha_power_true: 1.4 # Robertson et al., PMB 2017
    thermal_conductivity: 0.32 # [W/m/°C] Tissue Properties DB 
    specific_heat_capacity: 1313 # [J/kg/°C] Tissue Properties DB
  brain:
    sound_speed: 1546 # [m/s] Tissue Properties DB 
    density: 1046 # [kg/m^3], ITRUSST benchmarks or waterDensity(temp_0)
    alpha_0_true: 0.6 # ITRUSST benchmarks
    alpha_power_true: 1
    thermal_conductivity: 0.51 # [W/m/°C] Tissue Properties DB 
    specific_heat_capacity: 3630 # [J/kg/°C] Tissue Properties DB
  skin:
    sound_speed: 1610 # [m/s], ITRUSST benchmarks 
    density: 1090 # [kg/m^3], ITRUSST benchmarks
    alpha_0_true: 0.4 # ITRUSST benchmarks
    alpha_power_true: 1
    thermal_conductivity: 0.37 # [W/m/°C] Tissue Properties DB 
    specific_heat_capacity: 3391 # [J/kg/°C] Tissue Properties DB
  skull_trabecular: # trabecular bone
    sound_speed: 2300 # [m/s], ITRUSST benchmarks 
    density: 1700 # [kg/m^3], ITRUSST benchmarks
    alpha_0_true: 21.1 # benchmark Aubry et al., 2022 [8 at 500 kHz]
    alpha_power_true: 1.4 # Robertson et al., PMB 2017
    thermal_conductivity: 0.32 # [W/m/°C] Tissue Properties DB 
    specific_heat_capacity: 1313 # [J/kg/°C] Tissue Properties DB
  skull_cortical: # cortical bone
    sound_speed: 2800 # [m/s], ITRUSST benchmarks 
    density: 1850 # [kg/m^3], ITRUSST benchmarks
    alpha_0_true: 10.5 # benchmark Aubry et al., 2022 [4 at 500 kHz]
    alpha_power_true: 1.4 # Robertson et al., PMB 2017
    thermal_conductivity: 0.32 # [W/m/°C] Tissue Properties DB 
    specific_heat_capacity: 1313 # [J/kg/°C] Tissue Properties DB
```
